CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 0.8 --dataset dblp  --n-gaussian 5 --walk-lenght 80 --precompute-rw 10  --epoch 10 --epoch-embedding 10  --epoch-embedding-init 20 --beta .5  --alpha 1. --gamma 5. --lr 50   --negative-sampling 8  --context-size 20  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id dblp-2D-EM-TEST-13  --size 2  --seed 235 --batch-size 10000
CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 0.8 --dataset dblp  --n-gaussian 5 --walk-lenght 80 --precompute-rw 1  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 200 --beta .5  --alpha 1. --gamma 5. --lr 50   --negative-sampling 8  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id dblp-3D-EM-TEST-13  --size 3  --seed 235 --batch-size 10000
CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 0.8 --dataset dblp  --n-gaussian 5 --walk-lenght 80 --precompute-rw 1  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 200 --beta .5  --alpha 1. --gamma 5. --lr 50   --negative-sampling 8  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id dblp-6D-EM-TEST-13  --size 6  --seed 235 --batch-size 10000
CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 0.8 --dataset dblp  --n-gaussian 5 --walk-lenght 80 --precompute-rw 1  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 200 --beta .5  --alpha 1. --gamma 5. --lr 50   --negative-sampling 8  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id dblp-10D-EM-TEST-13 --size 10 --seed 235 --batch-size 10000


CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 0.8 --dataset dblp  --n-gaussian 5 --walk-lenght 80 --precompute-rw 1  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 200 --beta .5  --alpha 1. --gamma 5. --lr 50   --negative-sampling 8  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id dblp-2D-EM-TEST-14  --size 2  --seed 233 --batch-size 10000
CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 0.8 --dataset dblp  --n-gaussian 5 --walk-lenght 80 --precompute-rw 1  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 200 --beta .5  --alpha 1. --gamma 5. --lr 50   --negative-sampling 8  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id dblp-3D-EM-TEST-14  --size 3  --seed 233 --batch-size 10000
CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 0.8 --dataset dblp  --n-gaussian 5 --walk-lenght 80 --precompute-rw 1  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 200 --beta .5  --alpha 1. --gamma 5. --lr 50   --negative-sampling 8  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id dblp-6D-EM-TEST-14  --size 6  --seed 233 --batch-size 10000
CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 0.8 --dataset dblp  --n-gaussian 5 --walk-lenght 80 --precompute-rw 1  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 200 --beta .5  --alpha 1. --gamma 5. --lr 50   --negative-sampling 8  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id dblp-10D-EM-TEST-14 --size 10 --seed 233 --batch-size 10000

CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 0.8 --dataset dblp  --n-gaussian 5 --walk-lenght 80 --precompute-rw 1  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 200 --beta .5  --alpha 1. --gamma 5. --lr 50   --negative-sampling 8  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id dblp-2D-EM-TEST-15  --size 2  --seed 234 --batch-size 10000
CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 0.8 --dataset dblp  --n-gaussian 5 --walk-lenght 80 --precompute-rw 1  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 200 --beta .5  --alpha 1. --gamma 5. --lr 50   --negative-sampling 8  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id dblp-3D-EM-TEST-15  --size 3  --seed 234 --batch-size 10000
CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 0.8 --dataset dblp  --n-gaussian 5 --walk-lenght 80 --precompute-rw 1  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 200 --beta .5  --alpha 1. --gamma 5. --lr 50   --negative-sampling 8  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id dblp-6D-EM-TEST-15  --size 6  --seed 234 --batch-size 10000
CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 0.8 --dataset dblp  --n-gaussian 5 --walk-lenght 80 --precompute-rw 1  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 200 --beta .5  --alpha 1. --gamma 5. --lr 50   --negative-sampling 8  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id dblp-10D-EM-TEST-15 --size 10 --seed 234 --batch-size 10000


CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1.0 --dataset dblp  --n-gaussian 5 --walk-lenght 60 --precompute-rw 4  --epoch 10 --epoch-embedding 10  --epoch-embedding-init 50 --beta 1.  --alpha 1. --gamma 5. --lr 1   --negative-sampling 8  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id dblp-10D-EM-TEST-18  --size 10  --seed 235 --batch-size 40000
