CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 60 --precompute-rw 1  --epoch 1 --epoch-embedding 50  --epoch-embedding-init 3600 --beta 1.  --alpha 1. --gamma 1. --lr  .8  --negative-sampling 5  --context-size 5  --cuda --embedding-optimizer exphsgd  --em-iter 20 --id wikipedia-2D-EM-TEST-19  --size 2  --seed 246 --batch-size 40000

python3.7 launcher_tools/evaluation_supervised_poincare.py --file /local/gerald/POINCARE-EM/wikipedia-2D-EM-TEST-19 

python3.7  launcher_tools/poincare_visualisation.py --file /local/gerald/POINCARE-EM/wikipedia-2D-EM-TEST-19 
# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 60 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta 1.  --alpha 1. --gamma 1. --lr 50  --negative-sampling 5  --context-size 30  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-5D-EM-TEST-19  --size 5  --seed 246 --batch-size 40000
# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 60 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta 1.  --alpha 1. --gamma 1. --lr 50  --negative-sampling 5  --context-size 30  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-10D-EM-TEST-19  --size 10  --seed 246 --batch-size 40000

# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta .1  --alpha 1. --gamma 1. --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-2D-EM-TEST-20  --size 2  --seed 246 --batch-size 40000
# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta .1  --alpha 1. --gamma 1. --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-5D-EM-TEST-20  --size 5  --seed 246 --batch-size 40000
# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta .1  --alpha 1. --gamma 1. --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-10D-EM-TEST-20  --size 10  --seed 246 --batch-size 40000

# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta .1  --alpha 1. --gamma .1 --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-2D-EM-TEST-21 --size 2  --seed 246 --batch-size 40000
# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta .1  --alpha 1. --gamma .1 --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-5D-EM-TEST-21 --size 5  --seed 246 --batch-size 40000
# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta .1  --alpha 1. --gamma .1 --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-10D-EM-TEST-21 --size 10  --seed 246 --batch-size 40000

# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta 1.  --alpha 1. --gamma 1. --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-2D-EM-TEST-22  --size 2  --seed 246 --batch-size 40000
# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta 1.  --alpha 1. --gamma 1. --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-5D-EM-TEST-22  --size 5  --seed 246 --batch-size 40000
# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta 1.  --alpha 1. --gamma 1. --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-10D-EM-TEST-22  --size 10  --seed 246 --batch-size 40000

# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta .1  --alpha 1. --gamma 1. --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-2D-EM-TEST-23  --size 2  --seed 246 --batch-size 40000
# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta .1  --alpha 1. --gamma 1. --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-5D-EM-TEST-23  --size 5  --seed 246 --batch-size 40000
# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta .1  --alpha 1. --gamma 1. --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-10D-EM-TEST-23  --size 10  --seed 246 --batch-size 40000

# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta .1  --alpha 1. --gamma .1 --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-2D-EM-TEST-24 --size 2  --seed 246 --batch-size 40000
# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta .1  --alpha 1. --gamma .1 --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-5D-EM-TEST-24 --size 5  --seed 246 --batch-size 40000
# CUDA_VISIBLE_DEVICES=0 python3.7 launcher_tools/experiment_poincare_alternate.py --loss-aggregation mean --distance-coef 1. --dataset wikipedia  --n-gaussian 40 --walk-lenght 80 --precompute-rw 5  --epoch 10 --epoch-embedding 50  --epoch-embedding-init 100 --beta .1  --alpha 1. --gamma .1 --lr 1  --negative-sampling 5  --context-size 10  --cuda --embedding-optimizer exphsgd  --em-iter 20  --id wikipedia-10D-EM-TEST-24 --size 10  --seed 246 --batch-size 40000
python3.7 launcher_tools/evaluation_classifier_poincare.py --file /local/gerald/AISTAT-R-log/wikipedia-10D/